// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kif.proto

package kif

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FinishedStatus_Id int32

const (
	FinishedStatus_NOT_FINISHED    FinishedStatus_Id = 0
	FinishedStatus_SUSPEND         FinishedStatus_Id = 1
	FinishedStatus_SURRENDER       FinishedStatus_Id = 2
	FinishedStatus_DRAW            FinishedStatus_Id = 3
	FinishedStatus_REPETITION_DRAW FinishedStatus_Id = 4
	FinishedStatus_CHECKMATE       FinishedStatus_Id = 5
	FinishedStatus_OVER_TIME_LIMIT FinishedStatus_Id = 6
	FinishedStatus_FOUL_LOSS       FinishedStatus_Id = 7
	FinishedStatus_FOUL_WIN        FinishedStatus_Id = 8
	FinishedStatus_NYUGYOKU_WIN    FinishedStatus_Id = 9
)

var FinishedStatus_Id_name = map[int32]string{
	0: "NOT_FINISHED",
	1: "SUSPEND",
	2: "SURRENDER",
	3: "DRAW",
	4: "REPETITION_DRAW",
	5: "CHECKMATE",
	6: "OVER_TIME_LIMIT",
	7: "FOUL_LOSS",
	8: "FOUL_WIN",
	9: "NYUGYOKU_WIN",
}

var FinishedStatus_Id_value = map[string]int32{
	"NOT_FINISHED":    0,
	"SUSPEND":         1,
	"SURRENDER":       2,
	"DRAW":            3,
	"REPETITION_DRAW": 4,
	"CHECKMATE":       5,
	"OVER_TIME_LIMIT": 6,
	"FOUL_LOSS":       7,
	"FOUL_WIN":        8,
	"NYUGYOKU_WIN":    9,
}

func (x FinishedStatus_Id) String() string {
	return proto.EnumName(FinishedStatus_Id_name, int32(x))
}

func (FinishedStatus_Id) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dd923ea989406123, []int{2, 0}
}

type Piece_Id int32

const (
	Piece_NULL      Piece_Id = 0
	Piece_GYOKU     Piece_Id = 1
	Piece_HISHA     Piece_Id = 2
	Piece_RYU       Piece_Id = 3
	Piece_KAKU      Piece_Id = 4
	Piece_UMA       Piece_Id = 5
	Piece_KIN       Piece_Id = 6
	Piece_GIN       Piece_Id = 7
	Piece_NARI_GIN  Piece_Id = 8
	Piece_KEI       Piece_Id = 9
	Piece_NARI_KEI  Piece_Id = 10
	Piece_KYOU      Piece_Id = 11
	Piece_NARI_KYOU Piece_Id = 12
	Piece_FU        Piece_Id = 13
	Piece_TO        Piece_Id = 14
)

var Piece_Id_name = map[int32]string{
	0:  "NULL",
	1:  "GYOKU",
	2:  "HISHA",
	3:  "RYU",
	4:  "KAKU",
	5:  "UMA",
	6:  "KIN",
	7:  "GIN",
	8:  "NARI_GIN",
	9:  "KEI",
	10: "NARI_KEI",
	11: "KYOU",
	12: "NARI_KYOU",
	13: "FU",
	14: "TO",
}

var Piece_Id_value = map[string]int32{
	"NULL":      0,
	"GYOKU":     1,
	"HISHA":     2,
	"RYU":       3,
	"KAKU":      4,
	"UMA":       5,
	"KIN":       6,
	"GIN":       7,
	"NARI_GIN":  8,
	"KEI":       9,
	"NARI_KEI":  10,
	"KYOU":      11,
	"NARI_KYOU": 12,
	"FU":        13,
	"TO":        14,
}

func (x Piece_Id) String() string {
	return proto.EnumName(Piece_Id_name, int32(x))
}

func (Piece_Id) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dd923ea989406123, []int{3, 0}
}

type Modifier_Id int32

const (
	Modifier_NULL    Modifier_Id = 0
	Modifier_PROMOTE Modifier_Id = 1
	Modifier_PUTTED  Modifier_Id = 2
)

var Modifier_Id_name = map[int32]string{
	0: "NULL",
	1: "PROMOTE",
	2: "PUTTED",
}

var Modifier_Id_value = map[string]int32{
	"NULL":    0,
	"PROMOTE": 1,
	"PUTTED":  2,
}

func (x Modifier_Id) String() string {
	return proto.EnumName(Modifier_Id_name, int32(x))
}

func (Modifier_Id) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dd923ea989406123, []int{4, 0}
}

type Header struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd923ea989406123, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Pos struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos) Reset()         { *m = Pos{} }
func (m *Pos) String() string { return proto.CompactTextString(m) }
func (*Pos) ProtoMessage()    {}
func (*Pos) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd923ea989406123, []int{1}
}

func (m *Pos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos.Unmarshal(m, b)
}
func (m *Pos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos.Marshal(b, m, deterministic)
}
func (m *Pos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos.Merge(m, src)
}
func (m *Pos) XXX_Size() int {
	return xxx_messageInfo_Pos.Size(m)
}
func (m *Pos) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos.DiscardUnknown(m)
}

var xxx_messageInfo_Pos proto.InternalMessageInfo

func (m *Pos) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Pos) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type FinishedStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishedStatus) Reset()         { *m = FinishedStatus{} }
func (m *FinishedStatus) String() string { return proto.CompactTextString(m) }
func (*FinishedStatus) ProtoMessage()    {}
func (*FinishedStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd923ea989406123, []int{2}
}

func (m *FinishedStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishedStatus.Unmarshal(m, b)
}
func (m *FinishedStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishedStatus.Marshal(b, m, deterministic)
}
func (m *FinishedStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishedStatus.Merge(m, src)
}
func (m *FinishedStatus) XXX_Size() int {
	return xxx_messageInfo_FinishedStatus.Size(m)
}
func (m *FinishedStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishedStatus.DiscardUnknown(m)
}

var xxx_messageInfo_FinishedStatus proto.InternalMessageInfo

type Piece struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Piece) Reset()         { *m = Piece{} }
func (m *Piece) String() string { return proto.CompactTextString(m) }
func (*Piece) ProtoMessage()    {}
func (*Piece) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd923ea989406123, []int{3}
}

func (m *Piece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Piece.Unmarshal(m, b)
}
func (m *Piece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Piece.Marshal(b, m, deterministic)
}
func (m *Piece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Piece.Merge(m, src)
}
func (m *Piece) XXX_Size() int {
	return xxx_messageInfo_Piece.Size(m)
}
func (m *Piece) XXX_DiscardUnknown() {
	xxx_messageInfo_Piece.DiscardUnknown(m)
}

var xxx_messageInfo_Piece proto.InternalMessageInfo

type Modifier struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Modifier) Reset()         { *m = Modifier{} }
func (m *Modifier) String() string { return proto.CompactTextString(m) }
func (*Modifier) ProtoMessage()    {}
func (*Modifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd923ea989406123, []int{4}
}

func (m *Modifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Modifier.Unmarshal(m, b)
}
func (m *Modifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Modifier.Marshal(b, m, deterministic)
}
func (m *Modifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Modifier.Merge(m, src)
}
func (m *Modifier) XXX_Size() int {
	return xxx_messageInfo_Modifier.Size(m)
}
func (m *Modifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Modifier.DiscardUnknown(m)
}

var xxx_messageInfo_Modifier proto.InternalMessageInfo

type Step struct {
	Seq                  int32             `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Dst                  *Pos              `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	FinishedStatus       FinishedStatus_Id `protobuf:"varint,3,opt,name=finished_status,json=finishedStatus,proto3,enum=kif.FinishedStatus_Id" json:"finished_status,omitempty"`
	Piece                Piece_Id          `protobuf:"varint,4,opt,name=piece,proto3,enum=kif.Piece_Id" json:"piece,omitempty"`
	Modifier             Modifier_Id       `protobuf:"varint,5,opt,name=modifier,proto3,enum=kif.Modifier_Id" json:"modifier,omitempty"`
	Src                  *Pos              `protobuf:"bytes,6,opt,name=src,proto3" json:"src,omitempty"`
	ThinkingSec          int32             `protobuf:"varint,7,opt,name=thinking_sec,json=thinkingSec,proto3" json:"thinking_sec,omitempty"`
	ElapsedSec           int32             `protobuf:"varint,8,opt,name=elapsed_sec,json=elapsedSec,proto3" json:"elapsed_sec,omitempty"`
	Notes                []string          `protobuf:"bytes,9,rep,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd923ea989406123, []int{5}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Step) GetDst() *Pos {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *Step) GetFinishedStatus() FinishedStatus_Id {
	if m != nil {
		return m.FinishedStatus
	}
	return FinishedStatus_NOT_FINISHED
}

func (m *Step) GetPiece() Piece_Id {
	if m != nil {
		return m.Piece
	}
	return Piece_NULL
}

func (m *Step) GetModifier() Modifier_Id {
	if m != nil {
		return m.Modifier
	}
	return Modifier_NULL
}

func (m *Step) GetSrc() *Pos {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *Step) GetThinkingSec() int32 {
	if m != nil {
		return m.ThinkingSec
	}
	return 0
}

func (m *Step) GetElapsedSec() int32 {
	if m != nil {
		return m.ElapsedSec
	}
	return 0
}

func (m *Step) GetNotes() []string {
	if m != nil {
		return m.Notes
	}
	return nil
}

type Kif struct {
	Headers              []*Header `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	Steps                []*Step   `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Kif) Reset()         { *m = Kif{} }
func (m *Kif) String() string { return proto.CompactTextString(m) }
func (*Kif) ProtoMessage()    {}
func (*Kif) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd923ea989406123, []int{6}
}

func (m *Kif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kif.Unmarshal(m, b)
}
func (m *Kif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kif.Marshal(b, m, deterministic)
}
func (m *Kif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kif.Merge(m, src)
}
func (m *Kif) XXX_Size() int {
	return xxx_messageInfo_Kif.Size(m)
}
func (m *Kif) XXX_DiscardUnknown() {
	xxx_messageInfo_Kif.DiscardUnknown(m)
}

var xxx_messageInfo_Kif proto.InternalMessageInfo

func (m *Kif) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Kif) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func init() {
	proto.RegisterEnum("kif.FinishedStatus_Id", FinishedStatus_Id_name, FinishedStatus_Id_value)
	proto.RegisterEnum("kif.Piece_Id", Piece_Id_name, Piece_Id_value)
	proto.RegisterEnum("kif.Modifier_Id", Modifier_Id_name, Modifier_Id_value)
	proto.RegisterType((*Header)(nil), "kif.Header")
	proto.RegisterType((*Pos)(nil), "kif.Pos")
	proto.RegisterType((*FinishedStatus)(nil), "kif.FinishedStatus")
	proto.RegisterType((*Piece)(nil), "kif.Piece")
	proto.RegisterType((*Modifier)(nil), "kif.Modifier")
	proto.RegisterType((*Step)(nil), "kif.Step")
	proto.RegisterType((*Kif)(nil), "kif.Kif")
}

func init() { proto.RegisterFile("kif.proto", fileDescriptor_dd923ea989406123) }

var fileDescriptor_dd923ea989406123 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x93, 0xcf, 0x4e, 0xdb, 0x4e,
	0x10, 0xc7, 0xb1, 0x1d, 0x3b, 0xf6, 0x38, 0x84, 0xd5, 0xfe, 0xd0, 0x4f, 0x56, 0x2f, 0x04, 0x57,
	0x55, 0x39, 0x54, 0x1c, 0xc2, 0x03, 0x54, 0x11, 0xd9, 0x90, 0x55, 0xe2, 0x3f, 0x5a, 0xdb, 0x45,
	0x39, 0x59, 0x69, 0xb2, 0x29, 0x16, 0x90, 0xa4, 0x59, 0x53, 0xc1, 0xdb, 0xf4, 0xd0, 0x53, 0x5f,
	0xa0, 0xb7, 0x3e, 0x5b, 0x35, 0xeb, 0x80, 0x04, 0x27, 0xcf, 0x7c, 0xf7, 0xe3, 0xdd, 0xef, 0xec,
	0xec, 0x80, 0x77, 0x5b, 0xad, 0xce, 0xb7, 0xbb, 0x4d, 0xbd, 0xa1, 0xd6, 0x6d, 0xb5, 0x0a, 0xfb,
	0xe0, 0x8c, 0xe5, 0x7c, 0x29, 0x77, 0x94, 0x42, 0x6b, 0x3d, 0xbf, 0x97, 0x81, 0xd1, 0x33, 0xce,
	0x3c, 0xa1, 0x63, 0x7a, 0x0c, 0xf6, 0x8f, 0xf9, 0xdd, 0x83, 0x0c, 0x4c, 0x2d, 0x36, 0x49, 0x78,
	0x0a, 0x56, 0xba, 0x51, 0xb4, 0x03, 0xc6, 0xa3, 0xa6, 0x6d, 0x61, 0x3c, 0x62, 0xf6, 0xa4, 0x31,
	0x5b, 0x18, 0x4f, 0xe1, 0x1f, 0x03, 0xba, 0xa3, 0x6a, 0x5d, 0xa9, 0x1b, 0xb9, 0xcc, 0xea, 0x79,
	0xfd, 0xa0, 0xc2, 0x5f, 0x06, 0x98, 0x7c, 0x49, 0x09, 0x74, 0xe2, 0x24, 0x2f, 0x47, 0x3c, 0xe6,
	0xd9, 0x98, 0x0d, 0xc9, 0x01, 0xf5, 0xa1, 0x9d, 0x15, 0x59, 0xca, 0xe2, 0x21, 0x31, 0xe8, 0x21,
	0x78, 0x59, 0x21, 0x04, 0x8b, 0x87, 0x4c, 0x10, 0x93, 0xba, 0xd0, 0x1a, 0x8a, 0xc1, 0x35, 0xb1,
	0xe8, 0x7f, 0x70, 0x24, 0x58, 0xca, 0x72, 0x9e, 0xf3, 0x24, 0x2e, 0xb5, 0xd8, 0x42, 0xfa, 0x72,
	0xcc, 0x2e, 0x27, 0xd1, 0x20, 0x67, 0xc4, 0x46, 0x26, 0xf9, 0xc2, 0x44, 0x99, 0xf3, 0x88, 0x95,
	0x53, 0x1e, 0xf1, 0x9c, 0x38, 0xc8, 0x8c, 0x92, 0x62, 0x5a, 0x4e, 0x93, 0x2c, 0x23, 0x6d, 0xda,
	0x01, 0x57, 0xa7, 0xd7, 0x3c, 0x26, 0xae, 0x76, 0x33, 0x2b, 0xae, 0x66, 0xc9, 0xa4, 0xd0, 0x8a,
	0x17, 0xfe, 0x36, 0xc0, 0x4e, 0x2b, 0xb9, 0x90, 0xe1, 0xcf, 0xc6, 0xb0, 0x0b, 0xad, 0xb8, 0x98,
	0x4e, 0xc9, 0x01, 0xf5, 0xc0, 0xd6, 0x24, 0x31, 0x30, 0x1c, 0xf3, 0x6c, 0x3c, 0x20, 0x26, 0x6d,
	0x83, 0x25, 0x66, 0x05, 0xb1, 0x10, 0x9c, 0x0c, 0x26, 0x05, 0x69, 0xa1, 0x54, 0x44, 0x03, 0x62,
	0x63, 0x30, 0xe1, 0x31, 0x71, 0x30, 0xb8, 0xe2, 0x71, 0x73, 0x7c, 0x3c, 0x10, 0xbc, 0xbc, 0xd2,
	0xc7, 0xe3, 0x3a, 0xe3, 0xc4, 0x7b, 0x91, 0x31, 0x03, 0xbd, 0xd3, 0x2c, 0x29, 0x88, 0x8f, 0xe6,
	0x1b, 0x1d, 0xd3, 0x0e, 0x75, 0xc0, 0x1c, 0x15, 0xe4, 0x10, 0xbf, 0x79, 0x42, 0xba, 0xe1, 0x05,
	0xb8, 0xd1, 0x66, 0x59, 0xad, 0x2a, 0xb9, 0x0b, 0x3f, 0xbe, 0x71, 0xeb, 0x43, 0x3b, 0x15, 0x49,
	0x94, 0xe4, 0x8c, 0x18, 0x14, 0xc0, 0x49, 0x8b, 0x3c, 0x67, 0x43, 0x62, 0x86, 0x7f, 0x4d, 0x68,
	0x65, 0xb5, 0xdc, 0x52, 0x02, 0x96, 0x92, 0xdf, 0xf7, 0x2d, 0xc4, 0x90, 0xbe, 0x03, 0x6b, 0xa9,
	0x6a, 0xdd, 0x46, 0xbf, 0xef, 0x9e, 0xe3, 0x5b, 0x49, 0x37, 0x4a, 0xa0, 0x48, 0x3f, 0xc3, 0xd1,
	0x6a, 0xdf, 0xd1, 0x52, 0xe9, 0x96, 0x06, 0x56, 0xcf, 0x38, 0xeb, 0xf6, 0xff, 0xd7, 0xdc, 0xeb,
	0x6e, 0x9f, 0xf3, 0xa5, 0xe8, 0xae, 0x5e, 0x49, 0xf4, 0x3d, 0xd8, 0x5b, 0xbc, 0xd8, 0xa0, 0xa5,
	0x7f, 0x3b, 0x6c, 0xb6, 0x47, 0x05, 0xe9, 0x66, 0x8d, 0x7e, 0x02, 0xf7, 0x7e, 0x5f, 0x51, 0x60,
	0x6b, 0x8e, 0x68, 0xee, 0xb9, 0x4c, 0x44, 0x5f, 0x08, 0xf4, 0xab, 0x76, 0x8b, 0xc0, 0x79, 0xeb,
	0x57, 0xed, 0x16, 0xf4, 0x14, 0x3a, 0xf5, 0x4d, 0xb5, 0xbe, 0xad, 0xd6, 0xdf, 0x4a, 0x25, 0x17,
	0x41, 0x5b, 0x97, 0xe9, 0x3f, 0x6b, 0x99, 0x5c, 0xd0, 0x13, 0xf0, 0xe5, 0xdd, 0x7c, 0xab, 0xb0,
	0x22, 0xb9, 0x08, 0x5c, 0x4d, 0xc0, 0x5e, 0x42, 0xe0, 0x18, 0xec, 0xf5, 0xa6, 0x96, 0x2a, 0xf0,
	0x7a, 0x16, 0xbe, 0x7f, 0x9d, 0x84, 0x11, 0x58, 0x93, 0x6a, 0x45, 0x3f, 0x40, 0xfb, 0x46, 0x8f,
	0x8e, 0x0a, 0x8c, 0x9e, 0x75, 0xe6, 0xf7, 0x7d, 0x6d, 0xa0, 0x19, 0x27, 0xf1, 0xbc, 0x46, 0x4f,
	0xc0, 0x56, 0xb5, 0xdc, 0xaa, 0xc0, 0xd4, 0x90, 0xa7, 0x21, 0xbc, 0x7f, 0xd1, 0xe8, 0x5f, 0x1d,
	0x3d, 0x8e, 0x17, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x02, 0xdb, 0x3b, 0x4d, 0x9b, 0x03, 0x00,
	0x00,
}
